backend/app.py
backend/requirements.txt
backend/test.sh

inspired by this [example](https://github.com/pallets/flask/blob/2.2.5/examples/tutorial/flaskr/auth.py)
```bash
curl localhost:5001/register \
--data "username=user" \
--data "firstname=firstname" \
--data "lastname=lastname" \
--data "email=email@email.com" \
--data "password=1234"
```
Look in table in database
```bash
docker exec postgres psql \
$(grep DATABASE_URL= .env | sed 's/DATABASE_URL=//') \
-c "select * from users;"
```

Backend: register

---

backend/Makefile
backend/requirements.txt

add into container
* black to format code
* pylint

Backend: tools

---

frontend/AngularApp/src/app/navbar/navbar.component.html
frontend/AngularApp/src/styles.scss

how can we delete the underline from the link?

frontend: add link on the main logo

---

backend/app.py
backend/test.sh

1. find the username in the database
2. check the password with hash
* use [flask session](https://flask.palletsprojects.com/en/3.0.x/quickstart/#sessions)

Backend: Login

---

frontend/AngularApp/src/app/register-profile/register-profile.component.html
frontend/AngularApp/src/app/register-profile/register-profile.component.ts

this is the new syntax used since Angular 17

change syntax for dynamically render list to the new @for

---

backend/app.py
backend/requirements.txt
backend/test.py
create-env.sh

https://flask-jwt-extended.readthedocs.io/en/stable/automatic_user_loading.html

backend: access token jwt

---

frontend/AngularApp/src/app/UI/navbar/navbar.component.html
frontend/AngularApp/src/app/UI/navbar/navbar.component.ts
frontend/AngularApp/src/app/app.routes.ts
frontend/AngularApp/src/app/auth.guard.ts
frontend/AngularApp/src/app/auth/auth.service.ts
frontend/AngularApp/src/app/guest.guard.ts
frontend/AngularApp/src/app/login/login.component.html
frontend/AngularApp/src/app/login/login.component.scss
frontend/AngularApp/src/app/login/login.component.ts
frontend/AngularApp/src/app/shared/models/token.ts

The token is kept in auth.service after successfully login.
Some navbar links are only visible if we have a token.
auth guard created to protect some routes from being visited by unregistered user.
guest guard to block registered user to go to '/login' and '/register'

Auth guard

---

frontend/AngularApp/src/app/UI/navbar/navbar.component.html
frontend/AngularApp/src/app/UI/navbar/navbar.component.ts
frontend/AngularApp/src/app/app.component.html
frontend/AngularApp/src/app/app.component.ts
frontend/AngularApp/src/app/login/login.component.ts

Add token to LocalStorage so we can stay logged in when reloading the page as the AppComponent check if a access_token is present in LocalStorage.
(this is not following good security practices, but I will change it when choosing a store for the app).
logout icon in the navbar, logs you out now and redirect to /login

add token to localStorage and logout function

---

backend/app.py
backend/db.py

> I learn about how to split function on many files.
> the goal is to split by topic, not by features.
I move function by function, step by step to avoid to make bad error.
I check every time with make test.

backend: reorganize code

---

Makefile
backend/app.py
backend/test.py
docker-compose.dev.yml
docker-compose.prod.yml

if you dislike one of them suggestion
```bash
git checkout suggestion
git revert ${COMMIT_ID}
git push
```
* `27dd8b8` test.py: add forgotten "/api"
* `f7b8924` app.py: remove extra re-added code
* `5bf2783` docker-compose: add name to images built
* `0594404` remove the daemon mode

Misc suggestion

---

backend/app.py
frontend/AngularApp/src/app/login/login.component.ts
frontend/AngularApp/src/app/register/register.component.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

created a user.service to handle all http calls that concerne the user (like login, register).
refactor code in components where calls where made before.

User service

---

frontend/AngularApp/src/app/profile/dummyUserData.ts
frontend/AngularApp/src/app/profile/general-profile/general-profile.component.html
frontend/AngularApp/src/app/profile/general-profile/general-profile.component.ts
frontend/AngularApp/src/app/profile/modify-general/modify-general.component.html
frontend/AngularApp/src/app/profile/modify-general/modify-general.component.ts
frontend/AngularApp/src/app/profile/modify-interests/modify-interests.component.html
frontend/AngularApp/src/app/profile/profile.component.ts
frontend/AngularApp/src/app/register/register.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

The data modify by the user is send to the end point: "/modify-general" (this endpoint should be created)
The  shape of the data send can be found in shared/models/data-to-api/use.ts

Modify data to backend

---

frontend/AngularApp/src/app/app.config.ts

Implement a http interceptor to add the token in every request header.
And also console.log every request for now.

add token interceptor

---

frontend/AngularApp/src/app/app.config.ts
frontend/AngularApp/src/app/profile/modify-email/modify-email.component.html
frontend/AngularApp/src/app/profile/modify-email/modify-email.component.ts
frontend/AngularApp/src/app/profile/modify-general/modify-general.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

email is send to API to "/modify-email" endpoint.
the shape of the data is { email: string}
password is send to API to "/modify-password" endpoint.
the shape of the data is { currentPassword: string,  newPassword: string}

Email passwd to api

---

postgres-init/init.sql

Create more necessary tables + populate interests table.

Db tables creation

---

postgres-init/init.sql

Trigger to check values on every create or update in users table and update profile_complete.

add new trigger

---

backend/Makefile
backend/app.py
backend/db.py
backend/test.py

Create the route `/api/modify-general`, update a users row

Backend: modify general

---

backend/Makefile
backend/app.py
backend/app_utils.py
backend/db.py
backend/test.py
backend/test_utils.py

* remove useless variable
* create check_request_json in app_utils file
* remove useless lines
* delete /drop
* delete /create
> no more need to create table
> init.sql create tables
* remove extra comment
* Create `/api/deleteme`
> delete the user with jwt token
* check content code
* remove extra import
* rename function name
> api was extra and useless
* move util function in utils file
* uniform print error
* delete drop_table & create_table
* Makefile: adapt name

backend: refactor

---

backend/app.py
backend/app_utils.py
backend/db.py
backend/test.py
backend/test_utils.py
create-env.sh

* 7c3e37a check the number of picture uploaded
* 7e43e11 set profile picture in db
* a3ad79e modify profile picture
* fdaaa3f delete image with the user
* ea93169 db get user image
* ab1c8db db upload pictures
* 822e956 make unique filename and append in array
* 325f8d9 accept many pictures
* b875f00 upload one file
* b133822 create get_profile_picture_name
* 27619e6 check limit of pictures
* e1b55e5 fix expected values
* 9627397 modify-profile-picture
* 6af4cd5 send many files
* 0515069 check_post_token_file
* 792d53c create db_fetchone
* f67e2dc use function db_query
* 503c23b move flaskprint
* e9f500f remove docstring
* 781ccf7 add flask upload folder

Backend: pictures

---

backend/app.py
backend/app_utils.py
backend/db.py
backend/test.py
postgres-init/init.sql

* ffd5037 get/modify-interests
* 7a713ad get/modify-interest
* 862a801 user_interests: remove primary key
* 1135f69 create db_query_for
* 1e7ed8b delete query variable
* b7033cb use db_query for deleteme

Backend: interests

---

backend/app.py
backend/app_utils.py
backend/test.py
backend/test_utils.py

- compare json content instead string litteral
> We cannot check array content because the db
> do not sort every time in the same way
- remove all interests
- check only if there is a key, value can be null
> in this way we can remove all interests from a user

Backend: interest can be null

---

README.adoc

add frameworks section to the readme

documentation

---

backend/app.py
backend/app_utils.py
backend/db.py
backend/test.py
backend/test_utils.py
create-env.sh

We can access to images with a JWT by route `/api/images/<filename>`.
Route modify-pictures become pictures and send an array of URLs.
Test the users data.
* 0e282e9 picture return an array of pictures
* 043cbe6 add key to array
* 921f948 get image return an array
* 78a4c4a rename modify pictures by pictures
* d4dfdee modify picture split function
* ffee20d add url into images
* 255eba1 serve images
* 65a8d7f check users data
* 86add94 update for receive url array
* 7ae06fe check when 0 images
* 2538768 create pictures function
* 073299f add backend url
* 03e4be2 import: only one from

Backend: images

---

frontend/AngularApp/src/app/login/login.component.ts
frontend/AngularApp/src/app/profile/interests/interests.component.ts
frontend/AngularApp/src/app/profile/modify-email/modify-email.component.ts
frontend/AngularApp/src/app/profile/modify-general/modify-general.component.ts
frontend/AngularApp/src/app/profile/modify-interests/modify-interests.component.ts
frontend/AngularApp/src/app/profile/modify-pictures/modify-pictures.component.ts
frontend/AngularApp/src/app/profile/profile.component.html
frontend/AngularApp/src/app/profile/profile.component.ts
frontend/AngularApp/src/app/register/register.component.ts
frontend/AngularApp/src/app/shared/services/user.requests.service.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

Old userService is now userRequestsService.
userService now will hold stats and methods to update stats for all user related data.
For now interests are managed by userService.
Componenents can call getInterests() or modifyInterests()
and all the logic and stats are in the service.

Front interests

---

backend/app.py
backend/db.py
backend/test.py

PUT to update/read email value from user
GET to read email value from user

backend: email

---

backend/matcha/auth.py
frontend/AngularApp/src/app/app.routes.ts
frontend/AngularApp/src/app/login/login.component.html
frontend/AngularApp/src/app/reset-password/reset-password.component.html
frontend/AngularApp/src/app/reset-password/reset-password.component.scss
frontend/AngularApp/src/app/reset-password/reset-password.component.ts
frontend/AngularApp/src/app/shared/services/user.requests.service.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

Login password rests

---

backend/matcha/app_utils.py
backend/matcha/db.py
backend/matcha/pictures.py
backend/test.py
backend/test_utils.py
frontend/AngularApp/src/app/profile/modify-pictures/modify-pictures.component.html
frontend/AngularApp/src/app/profile/modify-pictures/modify-pictures.component.ts
frontend/AngularApp/src/app/profile/modify-pictures/picture-preview/picture-preview.component.html
frontend/AngularApp/src/app/profile/modify-pictures/picture-preview/picture-preview.component.scss
frontend/AngularApp/src/app/profile/modify-pictures/picture-preview/picture-preview.component.ts
frontend/AngularApp/src/app/profile/pictures-profile/pictures-profile.component.html
frontend/AngularApp/src/app/profile/pictures-profile/pictures-profile.component.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

select profile picture by clicking on a picture in /profile.
(now the backend doesn't find the picture selected as profile pic as the two names don't match)

delete profile selection on upload pictures

---

frontend/AngularApp/src/app/UI/navbar/navbar.component.scss
frontend/AngularApp/src/app/reset-password/reset-password.component.ts

As the name of the branch doesn't tell you, there is no hamburger menu on mobile.

no hamburger, no logo on mobile

---

backend/Makefile
backend/fakedata/faker.json
backend/matcha/db.py
backend/matcha/users.py
backend/populate.py
backend/test.py
backend/test_utils.py
frontend/AngularApp/src/app/browsing/user-list/user-item/user-item.component.html
frontend/AngularApp/src/app/browsing/user-list/user-item/user-item.component.ts
frontend/AngularApp/src/app/browsing/user-list/user-list.component.html
frontend/AngularApp/src/app/browsing/user-list/user-list.component.scss
frontend/AngularApp/src/app/browsing/user-list/user-list.component.ts

display public data from other user -> will do this in chat component.

Feat: get profile by username

---

backend/matcha/db.py
backend/matcha/users.py
frontend/AngularApp/src/app/app.config.ts
frontend/AngularApp/src/app/app.routes.ts
frontend/AngularApp/src/app/browsing/browsing.component.ts
frontend/AngularApp/src/app/browsing/user-detail/user-detail.component.html
frontend/AngularApp/src/app/browsing/user-detail/user-detail.component.scss
frontend/AngularApp/src/app/browsing/user-detail/user-detail.component.ts
frontend/AngularApp/src/app/browsing/user-list/user-item/user-item.component.html
frontend/AngularApp/src/app/browsing/user-list/user-item/user-item.component.ts
frontend/AngularApp/src/app/browsing/user-list/user-list.component.html
frontend/AngularApp/src/app/browsing/user-list/user-list.component.ts
frontend/AngularApp/src/app/profile/email-passwd/email-passwd.component.ts
frontend/AngularApp/src/app/profile/general-profile/general-profile.component.ts
frontend/AngularApp/src/app/profile/modify-email/modify-email.component.ts
frontend/AngularApp/src/app/profile/modify-general/modify-general.component.ts
frontend/AngularApp/src/app/profile/modify-pictures/modify-pictures.component.ts
frontend/AngularApp/src/app/profile/pictures-profile/pictures-profile.component.ts
frontend/AngularApp/src/app/profile/profile.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/services/user.requests.service.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

on `/browsing` a list of users is displayed (dummy data for now) and when clicking on the user card, we get to `/browsing/username`
where the data is requested  with GET `/users?username=username`
For example, a homosexual men should only get men.

Browsing user detail

---

backend/matcha/db.py
backend/matcha/users.py

backend: browsing do not return user himself

---

frontend/AngularApp/src/app/browsing/browsing.component.ts
frontend/AngularApp/src/app/browsing/user-detail/user-detail.component.html
frontend/AngularApp/src/app/browsing/user-detail/user-detail.component.ts
frontend/AngularApp/src/app/browsing/user-list/user-list.component.html
frontend/AngularApp/src/app/browsing/user-list/user-list.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/models/emptyUser.ts
frontend/AngularApp/src/app/shared/services/potentialMatch.service.ts
frontend/AngularApp/src/app/shared/services/user.requests.service.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

click on a potential match navigates to the user profile page.

Match detail

---

frontend/AngularApp/src/app/search/user-list/user-item/user-item.component.scss
frontend/AngularApp/src/app/search/user-list/user-item/user-item.component.ts
frontend/AngularApp/src/app/search/user-list/user-list.component.ts
frontend/AngularApp/src/app/shared/services/potentialMatch.service.ts
frontend/AngularApp/src/app/shared/services/user.requests.service.ts

add a post request when visiting someone profile page.

Various impr

---

frontend/AngularApp/src/app/UI/navbar/navbar.component.html
frontend/AngularApp/src/app/UI/navbar/navbar.component.ts
frontend/AngularApp/src/app/profile/modify-general/modify-general.component.ts
frontend/AngularApp/src/app/profile/profile.component.html
frontend/AngularApp/src/app/profile/profile.component.scss
frontend/AngularApp/src/app/profile/profile.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/services/user.requests.service.ts
frontend/AngularApp/src/app/shared/services/user.service.ts
postgres-init/init.sql

user must complete profile before searching or chatting

Profile next level

---

backend/matcha/db.py
backend/matcha/users.py

* 8e5dafe add profile picture in user per username
* 3e48161 add pictures in user per username
* 10a6aac add interests in user per username
* fd549c2 add bio in user per username
* 4033181 fix db error

Backend users

---

backend/matcha/db.py
backend/matcha/users.py

backend: browsing give profile url

---

frontend/AngularApp/src/app/profile/general-profile/general-profile.component.ts
frontend/AngularApp/src/app/search/user-list/user-list.component.html
frontend/AngularApp/src/app/search/user-list/user-list.component.ts
frontend/AngularApp/src/app/shared/pipes/filterMatches.pipe.ts
frontend/AngularApp/src/environments/environment.prod.ts
frontend/AngularApp/src/environments/environment.ts

Potential matches can be filter by age and fame rating compared to user values.

Filter people

---

README.adoc
frontend/AngularApp/src/app/shared/services/error.service.spec.ts

add testing for a simple service: errorService
tests can be run with:
`docker exec -it angular-dev npm test`

add errorService test

---

frontend/AngularApp/src/app/shared/utils/displayUtils.spec.ts

Testing some pure typescript function for learning purposes.
You run the test with this command:
`docker exec -it angular-dev npm test`

add display utils tests

---

frontend/AngularApp/package-lock.json

Update package-lock of dependencies

frontend: update package-lock

---

frontend/AngularApp/src/app/search/user-list/user-item/user-item.component.html
frontend/AngularApp/src/app/search/user-list/user-item/user-item.component.spec.ts

Add test to check the values inside the template component once it's rendered.

Test continue

---

frontend/AngularApp/src/app/chat/chatroom/chatroom.component.html
frontend/AngularApp/src/app/chat/chatroom/chatroom.component.scss
frontend/AngularApp/src/app/chat/chatroom/chatroom.component.ts
frontend/AngularApp/src/app/chat/chatroom/display-messages/display-messages.component.scss

Change chat UI, can handle long messages, auto scroll.

chat new UI

---

backend/matcha/services/users.py
frontend/AngularApp/src/app/profile/interests/interests.component.html
frontend/AngularApp/src/app/profile/interests/interests.component.ts
frontend/AngularApp/src/app/profile/modify-interests/modify-interests.component.ts
frontend/AngularApp/src/app/profile/profile.component.ts
frontend/AngularApp/src/app/search/search.component.ts
frontend/AngularApp/src/app/search/user-list/user-list.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/models/emptyUser.ts
frontend/AngularApp/src/app/shared/pipes/filterMatches.pipe.ts
frontend/AngularApp/src/app/shared/services/http.requests.service.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

the filter: by Interests is working.
interests are transmitted to the front inside user's data, not separately anymore.

Filter interest

---

README.adoc
backend/matcha/db/db.py
backend/matcha/db/position.py
backend/matcha/db/utils.py
backend/matcha/geoapi/latlon_to_address.py
backend/matcha/routes/__init__.py
backend/matcha/routes/position.py
backend/matcha/services/position.py
backend/requirements.txt
backend/test.py
postgres-init/init.sql

positon is send to backend on `/api/position` endpoint.
If the user accepts to share its location -> { latitude: number; longitude: number } is send.
Latitude range: [−90, 90]
Longitude range: [−180, 180]
If the user refuse to share its location -> { latitude = 999 ; longitude = 999 } is send.
> set default to Null
```bash
curl  https://nominatim.openstreetmap.org/reverse\?lat\=46.532327\&lon\=6.591987
```
[Geocode](https://geocode.maps.com)

feat send position to backend

---

Makefile
backend/matcha/routes/pictures.py
backend/matcha/services/pictures.py
backend/test.py
backend/test_utils.py
cliff.toml
frontend/AngularApp/src/app/shared/services/http.requests.service.ts

Mofify route name
- *(picture)* Rename route
- *(naming)* Remove modify
- *(utils)* Add an exception handling
- *(picture)* Adapt with the new route name

Rename modify profile picture

---

frontend/AngularApp/src/app/search/research/research.component.ts
frontend/AngularApp/src/app/search/user-list/user-list.component.html
frontend/AngularApp/src/app/search/user-list/user-list.component.ts
frontend/AngularApp/src/app/shared/services/potentialMatch.service.ts

filter matches are stored and used when come back to search page

filter matches

---

backend/matcha/db/db.py
backend/matcha/services/browsing.py
backend/test.py
frontend/AngularApp/src/app/UI/navbar/navbar.component.html
frontend/AngularApp/src/app/auth.guard.ts

- *(browsing)* Check if the profile is completed
- *(profile)* Is completed
- *(browsing)* Check not completed error

Browsing check profile complete

---

backend/matcha/services/chat.py
backend/matcha/services/profile.py
backend/test.py

- *(chat)* Username not found
- *(profile)* Bad username
- *(profile)* Check bad username
- *(profile)* Add a finale simple quote
- *(profile)* Single quote in bio
- *(chat)* Username not found

Fix profile username

---

backend/matcha/services/profile.py
backend/matcha/websocket/socket_manager.py
backend/test.py
frontend/AngularApp/src/app/search/user-detail/user-detail.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/models/emptyUser.ts

- *(socket)* Add decorator classmethod
- *(profile)* Return connected bool
- *(socket)* Create is_connected function
- *(profile)* Connected information

Profile: is connected

---

backend/matcha/db/visit.py
backend/matcha/db/visite.py
backend/matcha/services/profile.py
backend/test.py
cliff.toml

- *(profile)* Return visitedBy
- *(visit)* Insert visite by
- *(visit)* Get visit by
- *(profile)* Add visitedBy

Visited by

---

frontend/AngularApp/src/app/profile/general-profile/general-profile.component.html
frontend/AngularApp/src/app/profile/modify-general/modify-general.component.ts
frontend/AngularApp/src/app/profile/profile.component.ts
frontend/AngularApp/src/app/shared/models/data-to-api/user.ts
frontend/AngularApp/src/app/shared/services/http.requests.service.ts
frontend/AngularApp/src/app/shared/services/localization.service.ts

- Frontend send user coordinates, browser coordinates or default coordinates: 
(latitude: 999, longitude: 0, accuracy: 0,) to the backend.

front send coordinates to backend

---

backend/matcha/db/like.py
backend/matcha/db/notification.py
backend/matcha/services/chat.py
backend/matcha/services/like.py
backend/matcha/services/profile.py
backend/matcha/utils.py
backend/matcha/websocket/notification.py
backend/test.py
frontend/AngularApp/src/app/search/user-detail/user-detail.component.ts
frontend/AngularApp/src/app/shared/services/http.requests.service.ts
frontend/AngularApp/src/app/shared/services/potentialMatch.service.ts
frontend/AngularApp/src/app/shared/services/socket.service.ts

- *(like)* Rename dislike per unlike
- *(like)* Remove send by websocket
- *(like)* Unlike is notification
- *(like)* Create function get_id
- *(like)* Implement function
- *(profile)* Notify the user visited
- *(chat)* Notify after a message
- *(utils)* Move function
- *(noti)* Send notification by web socket
- *(like)* Change dislike per unlike
- *(like)* Check the validity of username
- *(socket)* Bad variable name
- *(ws)* Move function
- *(like)* Dislike -> unlike
- *(like)* Like/unlike/like to check notification
- *(notification)* Visited user
- *(notification)* Chat

Notification

---

backend/matcha/services/chat.py
backend/matcha/websocket/chat.py
frontend/AngularApp/src/app/shared/services/socket.service.ts

- *(websocket)* Create send chat content
- *(chat)* Send chat message

Chat msg update

---

backend/matcha/services/interests.py

- *(interets)* Remove extra web socket message

back(interets): remove extra web socket message

---

backend/matcha/__init__.py

- *(jwt)* Refresh token
> according to [Refreshing Tokens](https://flask-jwt-extended.readthedocs.io/en/stable/refreshing_tokens.html)

back(jwt): refresh token

---

backend/matcha/__init__.py
backend/matcha/db/register.py
backend/matcha/services/register.py
backend/test.py

- *(register)* Set error code
- Format
- *(register)* Set error code

Register same username

---

README.adoc
backend/matcha/db/user.py
backend/matcha/routes/auth.py
backend/matcha/services/auth.py
backend/test.py
frontend/AngularApp/src/app/app.routes.ts
frontend/AngularApp/src/app/reset-password/reset-password.component.ts
frontend/AngularApp/src/app/reset-pwd-page/reset-pwd-page.component.html
frontend/AngularApp/src/app/reset-pwd-page/reset-pwd-page.component.scss
frontend/AngularApp/src/app/reset-pwd-page/reset-pwd-page.component.ts
frontend/AngularApp/src/app/shared/services/http.requests.service.ts
frontend/AngularApp/src/app/shared/services/user.service.ts

- *(auth)* Reset password send email
- *(reset)* Sent link and receive jwt
- *(route)* Create reset with jwt
- *(email)* Get email data
- *(user)* Create update password
- *(back)* Add forgotten import
- *(reset)* Explain the process
- *(reset)* Add test and move position
- *(reset-password)* Fix expected code
- *(reset)* Post with password

Reset password

---

backend/matcha/services/auth.py
backend/matcha/services/confirm.py

- *(confirm)* Use variable
- *(reset)* Add frontend link

Reset link

---

backend/matcha/services/auth.py
backend/matcha/services/confirm.py

back(mail): prod message

---

frontend/nginx.conf

prod(nginx): remove extra scop

---

Makefile
backend/matcha/db/user.py
backend/matcha/services/like.py
backend/matcha/services/profile.py
backend/test.py

- *(like)* Update the fame rating
- *(fame rating)* Fix an erro
- *(fame)* Rating
- *(make)* Use OR instead of pipe
- *(user)* Format
- *(profile)* Test the famerating

fame rating
